### PR TITLE
Accumulated minor changes

### LINKED ISSUE #984: Conflict of Optimized Relaxed Clock and Sampled Ancestors
A sudden IndexError in an analysis had me stumped for some time. I have now figured out why it happens, but not how to fix it.

Symptoms:

For the analysis that permits sampled ancestors, the Relaxed Clock dies with an index error somewhere in the branch-rates-aware narrow exchange (MetaNER) operator.
What happens is the following:
1. The relaxed clock mechanism sets the dimension of the rate parameter to “number of nodes in the tree – 1”, and the number of nodes at that point is correctly “number of tips × 2 – 1”. For Sinotibetan, this is 98 rates and 99 nodes for 50 tips, with the nodes numbered 0 to 98.
2. The model runs fine for several 100'000s of steps.
3. The MetaNER tries to propose an exchange, but trying to look up the node D with number 98 it dies with an IndexError.

For a moment I thought I might have started with a sampled ancestor and then a Jump added an internal node which would put the total number of nodes, and therefore branches, and therefore rates needed, up by one without adjusting the dimension of the rates parameter. But that's not the case, sampled ancestors are not degree-2 nodes, but tips with a branch length of 0.

Investigating closer, I was greatly confused, because I know that node D in the MetaNER is a child, and that node 98 is always the root. Except:

https://github.com/CompEvol/beast2/blob/4d95f0095d20a6999d2757299c629bfbbf14b94b/src/beast/evolution/tree/Tree.java#L322-L333

This method messes with that invariant, and makes Sampled Ancestors and Optimized Relaxed Clocks incompatible.
Why is it there? Why can Sampled Ancestors not just use the same `setRoot()` as everyone else?
Is there a way to get SA to work with an ORC (I'm willing to modify and test code and supply patches, as you know), or am I stuck with the generic Relaxed Clock with its convergence issues?
Should I cross-link this issue to the SA and ORC repositories?

### PR DESCRIPTION
**Pull request by Anaphory**
- Fix #984 (I'm not sure this fix is complete, that's why this PR is only in draft mode)
 - Incorporate #953 
 - Be slightly more explicit with an exception or two and attributes that used to be package-private but should be protected

### CODE REVIEW

**Comment by rbouckaert** [comment]
32b8a1e does not seem appropriate for v2.6.x. We are heading for [v2.7](http://rbouckaert.github.io/BEAST2.7/#/), which should be based on Java 11 and given the instability of Java preferably only gets released with a java 11 JRE included so it won't be necessary any more to have java version specific checks.

**Comment by rbouckaert** [comment]
cc9c16657edc51b23491f7c62badf682861183f9 & ceaf2f2 were the same as merged with #953?

**Comment by rbouckaert** [comment]
I am happy with making fields protected and very happy with improved error messages. The bits around setting node counts to deal with the SA operator missbehaviour I am not particularly in favour of.

**Comment by Anaphory** [comment]
Good points! Yes, this is a collection of various patches that I accumulated over time, and I'm happy to clean it up to a better standard.
I have submitted that PR to the SampledAncestors package and used it quite extensively on my end now, and not seen any more issues, so I think it solves the SA operator misbehaviour.

I thought I had also pushed the commit here that undid all that special handling of node counts, but I may have left traces behind even after after https://github.com/CompEvol/beast2/pull/987/commits/35264f6a520603dc644536b731fece4e6b008664 – so I think I'll have to aggregate a cleaner version history, so it's more transparent what's going on before you merge.

**Comment by rbouckaert** [comment]
Java 6 used to be bundled with OS X, but BEAST requires Java 8, which means users had to install Java 8 before being able to run BEAST. It produced a completely incomprehensible error message otherwise. So, now at startup BEAST always checks the java version number and produces a more reasonable error message. But that check has to happen with code that is Java 6 compatible, so a small number of classes are compiled for Java 6.

Anyway, a cleaned up version of the pull request will be very much appreciated! It would be great if it could make the v2.6.6 release, which is now in preparation.

**Comment by rbouckaert** [comment]
0bbf909 and 6544c79 are now included in b5926b6

**Pull request closed without merging**
