### PR TITLE
Analysis of uncertain character data

### PR DESCRIPTION
**Pull request by 1j**
In certain cases, character data is not known with complete certainty, for example with bases inferred from next generation sequencing data. 

The purpose of these changes is to allow BEAST2 to operate on uncertain character data, consisting of vectors of likelihoods of some other observed data (e.g. read counts) for each of the possible characters at each site. For example, the sequence 

AGC

might be replaced by the string

0.015,0.002,0.002,0.002; 4.7e-04,0.006,0.013,0.006; 0.00014,0.0018,8.6e-07,2.4e-07;

with each entry representing the likelihood of the observed data given the four possible bases at each site.

### CODE REVIEW

**Comment by tgvaughan** [comment]
Thanks for this Joe, looks useful!  We'll look this over and see whether it's okay to merge in before the next release.

**Comment by 1j** [comment]
Thanks Tim. I've been in email contact with Alexei, Remco and Arman about this, and it seems they were also considering something similar; hopefully it will be useful for others as well.

**Comment by armanbilge** [comment]
I just took a quick look at this, Joe, 

For example, `N`s and gaps `-` should be coded as `1,1,1,1`.

If you have a copy of Felsenstein's *Inferring Phylogenies* handy, you may want to have a look at "Handling ambiguity and error" in Chapter 16 (pp. 255–256).

**Comment by 1j** [comment]
Thanks for the comments Arman. I agree there's no need for the tip likelihoods to sum to unity, (Felsenstein at the bottom of p.255 seems to suggest that they should sum to unity in the case of uncertain data, but on the R-sig-phylo list he [recently made it clear](https://stat.ethz.ch/pipermail/r-sig-phylo/2015-January/003847.html) that this was not the intention). I think the key point is to regard the tip vectors as likelihoods of some other observed data (e.g. read counts) given the possible characters at tips, rather than prior probabilities of the unobserved characters at the tips.

I renamed some variables in the code to clarify the above points, removed the requirement for tip vectors to be normalised, and also rewrote the XML examples to use actual likelihoods computed under a simple multinomial model of read counts with sequencing errors. On these test examples, using the likelihood vectors at the tips leads a much better reconstruction of the tree posterior than simply using the error-prone ML estimates of the characters (I'll send a figure via email illustrating this).

As an aside, it's worth noting that setting gaps to be 1/4,1/4,1/4,1/4 rather than 1,1,1,1 would just multiply the likelihood by (1/4)<sup>#gaps</sup>. For a fixed alignment, this will just be a constant factor that will cancel out in the MH ratios, so it shouldn't make any difference to the inference. However, for non-uniform tip vectors representing likelihoods, the magnitude of the entries will indeed make a difference, so renormalising the tip likelihood vectors to sum to unity would not be a good idea in general.

**Pull request merged**
