### PR TITLE
AddOnManager/package management revamp

### PR DESCRIPTION
**Pull request by tgvaughan**
As requested by @rbouckaert, I've overhauled BEAST's package management system to pave the way for the 2.4 release.  The primary goal of this overhaul is to make version-specific package.xml files unnecessary by allowing a single repository XML file to house entries representing multiple versions of the same package.  That is, to address issue #467.

Accomplishing this has required me to make a number of fairly big changes to AddOnManager - the main class responsible for handling the discovery, installation and removal of packages in BEAST.  It has also required that I make a number of changes to the package management UI.  I think these changes are improvements, but of course that's up to everyone else to decide.

The main internal changes are as follows:

1. Single Package objects now represent zero or more versions available online and zero or one locally installed version of the package.

2. Versions are never directly referred to as strings, but rather instances of PackageVersion, which implements the Version interface that BEAST already has in place. (Internally of course they are still strings, but that's implementation detail.)  PackageVersion implements Comparable via a method that compares two versions to decide which is more recent.  For instance, 2.4 > 2.3.4b > 2.3.4a etc. (I did not invent the algorithm.  It seems to work very well.)

3. A new method `populatePackagesToInstall` takes an initial list of packages and pads out that list with dependencies that are compatible with the packages versions to be installed and those already installed.  If the dependencies cannot be resolved, a DependencyResolutionException is raised, which can be caught to identify the cause.

4. The `installPackages` method has been revamped.  It is no longer recursive and does not check for dependencies.  It simply installs a list of requested package versions as discovered by `populatePackagesToInstall`.

5. Similarly, `uninstallPackage` has been modified so that it avoids any dependency checking.  Instead, it simply uninstalls a single package.  The `getInstalledDependencyNames` method should be used first to determine whether uninstalling a package will break anything. This separation of the installation/removal operations from the dependency checking means that those operations can be used as part of larger installation/upgrading operations without throwing errors because of broken intermediate states.

6. A final important internal change is that the installed version of beast2 now appears as just anotehr package in the internal package database. This allows proper treatment of the beast2 version dependencies already in the version.xml and package.xml files.  This should make it relatively easy to move almost all of the core BEAST classes (with the exception of the package manager itself) out to an external package that can be automatically upgraded.  If we do this right, 2.4 could be the last release that users need to directly download from beast2.org.

The UI changes are best explained via the following figure:

packman

The most obvious change is the use of colours and bold font.  The packages whose most recent version is coloured GREEN are packages that can be safely upgraded to the most recent version.  Those that are also BOLD are packages that are currently installed and can be upgraded.

The packages whose most recent version is coloured RED cannot be upgraded to the most recent version because of a dependency problem.  The nature of the problem is explained in a message dialog that appears when the user attempts to install these packages.  (In both cases shown the problem is that the new versions rely on a newer version of BEAST.) Packages that are also BOLD are packages that are currently installed but cannot be upgraded due to dependency problems.

The other major change is the removal of the "install/uninstall dependencies" checkbox.  Every installation now automatically installs any required dependencies.  Attempting to uninstall one of these dependencies will fail - a message appears telling the user that the dependent package must be removed first.  (Uninstalling dependent packages automatically seems like quite surprising behaviour to me.)

Note that when multiple versions of a package are available, only the most recent will ever be installed by explicit request.  It is not possible, for example, to directly install an old version of BEASTLabs.  However, if BEASTLabs is not installed and the most recent version of some other package relies on an available older version of BEASTLabs, it is the older version which will be installed as the dependency.  This is not allowed if the most recent version of BEASTLabs is already installed though, as automatic downgrading of installed packages is forbidden.

What do you think?  Note that I don't intend this pull request to be accepted as is - at very least it needs some interactive rebasing to squish and rename those commits down to something a bit more in line with beast's commit naming policy.  However, it is certainly functional as is.  It's using the repository file `packages.xml` on CBAN as the main repo file.  This is unused by any current version of BEAST.  It includes entries representing fake versions of MASTER and EpiInf with unsatisfied dependencies to demonstrate the new UI.

### CODE REVIEW

**Comment by rbouckaert** [comment]
Hi Tim,

I like this very much -- looks like we can keep everything managed in a single packages.xml file and do away with the headache of updating multiple files! The GUI looks much prettier as well, and use of colour is intuitive.

One little detail: I'd like to keep BEASTVersion.getVersion() -- changing the getVersionString to getPrettyVersionString is fine (though not quite necessary), but changing the behaviour of getVersionString -- which is what the renaming does -- is confusing.

Remco

**Comment by tgvaughan** [comment]
Hi Remco, glad this is to your liking!  One thing that _will_ have to be changed before a merge is replacing the windows-specific behaviour of restarting BEAUti following package removal.  I was hoping that this might be unnecessary following java 1.7, but it seems that the jar loading mechanism in AddOnManager uses a single ClassLoader to handle loading all of the packages - and BEAST itself.  To fix this properly someone will have to experiment with replacing this single URLClassLoader with package-specific loaders.  Rumor has it that closing these classloaders with the new method close() should free up any files involved.  This is a pretty major refactor, so it's probably best to restore the original functionality for the moment and work on that issue separately.  (Do we have anybody with access to a Windows machine willing to have a look at this??)

Re the naming: yes, it's confusing to change the behaviour of an existing interface.  I did it because the method actually lies - it's not returning a Version (which is an existing type in beast) but rather a String. It just seemed a bit weird to have variables named `version` with type `Version` that implement a method `getVersion()`.  Changing it back shouldn't actually alter any of the new code though iirc, because `toString()` handles retrieving string representations for printing and otherwise there's no need to refer to a string at all.

**Comment by tgvaughan** [comment]
Oops, just noticed all of the code that depends on the old naming - oops!  I get your point now. :-)

**Comment by rbouckaert** [comment]
Yes the classloader stuff needs some attention. Will try to get a windows machine handy...

Any idea why this #501 is not listed as open issue on github?

**Comment by tgvaughan** [comment]
Because it's a pull request - they're tallied separately to issues.  It's listed under "open pull requests".

**Comment by tgvaughan** [comment]
I've added in support for jar-file delete failures.  Along with the toDeleteList file already in use for this purpose, I've had to create a toInstallList which continues an installation following BEAUti/beast restart.  This is to handle the case where delete failures happen during an upgrade.

I've also done an interactive rebase on the commits and squashed them all down to a single commit which references #467, so feel free to merge when ready.

**Pull request merged**
