### PR TITLE
Non binary trees

### PR DESCRIPTION
**Pull request by Anaphory**
Add some tests (not all of them very sophisticated, and so far restricted to trees nodes with 0, 1, or 2 children, no multifurcating trees yet) for how Beast deals with non-binary trees, and fix a few issues I found in the process so far.

### CODE REVIEW

**Comment by tgvaughan** [comment]
Hi @Anaphory, thanks for the PR!  It seems that the unit tests are failing though, perhaps you could have a look at this?  Also, as you seem to be working on non-binary trees, you might be interested in [pitchfork](https://github.com/tgvaughan/pitchfork). :-)

**Comment by Anaphory** [comment]
I have looked at the failing tests, in quite some depth.

For the likelihood tests, I have no idea why they fail. I can only assume that the likelihood calculation is somewhat dependent on the actual scaling of the partials calculated, but I have no independent way to calculate these likelihoods. (It also looks like they were calculated using Beast XMLs, so they are not generated from an independent source, either.)

I have absolutely no idea why the XML parser tests fail.

**Comment by tgvaughan** [comment]
Unfortunately we won't be able to merge this in until we figure out what's going on with these failing tests.

**Comment by rbouckaert** [comment]
Given the time passed, I think this can be closed now -- reopen if you think it is worth while.

**Comment by Anaphory** [comment]
Sounds good. I don't even remember what I wanted polytomies for. There may be useful fixes and/or observations in my commits, so please have a look if you revisit the topic of multifurcations, but I'm not sad to see it closed.

**Pull request closed without merging**
