### PR TITLE
UpDownOperator improvement - chosing different random index for each parameter in elementWise scaling

### PR DESCRIPTION
**Pull request by boskovav**
Allowing for scaling of a different index position for each multi-dimensional parameter to enable efficient parameter space exploration for constrained parameters such as in eg. birth rates in super-spreader models

### CODE REVIEW

**Review by tgvaughan — COMMENTED** [review]
Hey Veronika, thanks for the PR!  Just one tiny thing, is there any chance the conditional inside the loop causes any perceptible slow-down?  This is a very important operator for almost every analysis, so we should be super careful here.  What do you think @rbouckaert?

**Comment by boskovav** [comment]
Thanks for reviewing this, Tim! 
I just did a quick performance comparison. I used this UpDownOperator (with weight of 20.0 out of 22.9) within a BDMM model with 2-demes. I used it to scale up/down 2-dimensional R0betweenDemes and 2-dimensional R0WithinDemes parameters. On my Mac, when checking just the reported time needed per 1M samples I obtain the following numbers:
(Note: I obtained the time to 1Msamples by averaging the first 10 screen-reported times (with screen-logging every 1000th MCMC step))
- elementWise=true, differentRandomIndex=true :  40m 43s
- elementWise=true, differentRandomIndex=false : 39m 25s
- elementWise=true - with code before #63dd08d (ie no differentRandomIndex option/code) : 39m 37s

Then I thought that a more efficient implementation may be to have the  "if (differentRandomIndexInput.get())" before stepping to into the for loops that are actually scaling the parameters. If I do this, the time till 1M steps is the following:
- elementWise=true, differentRandomIndex=true :  40m 40s
- elementWise=true, differentRandomIndex=false : 39m 45s 

So at least for the 2-dimensional parameters the actual implementation does not make much difference in the runtime. 

Also, no matter the implementation I think the slow-down won't be huge in any case, since I have actually not seen any example xml files or, for that matter, heard of anyone mentioning using the "elementWise" option of the UpDownOperator. So, in most cases/analyses the part of the code that follows when "if (elementWiseInput.get())" evaluates to true, is skipped in anyways.

**Comment by tgvaughan** [comment]
Thanks a lot Veronika for looking into this.  You've convinced me that nothing will break as the result of this code. :-)

**Comment by boskovav** [comment]
Awesome :) Thank you, Tim!

**Pull request merged**
